import {writeFileSync} from 'node:fs';
import {graph,unpagedGraph,endingVariants,pickEnding} from '../data/story.js';
import {play} from './simulation.js';
import {average,rating} from '../js/state.js';
const rows=Object.values(unpagedGraph).filter(n=>!n.terminal).sort((a,b)=>a.chapter-b.chapter||a.id.localeCompare(b.id));
let md='# Story graph reference\n\nGenerated by `node tools/reference.js` from the shipped graph. Conditions and effects in the JavaScript data are authoritative. Entry point is `p01`; terminal is `epilogue`. Each event expands into the listed number of passages; `event~1` is its first passage when split, and the original ID is its final major decision. Intermediate decisions retain the event’s location and time. Their prose is partitioned, never duplicated.\n\n## Event routing\n\nTargets below are the final graph targets of each event’s major decision. Each intermediate passage has two authored responses and a persistent effect before continuing within the event. The graph is acyclic. Optional events rejoin the semester; only one alternative is visited per branch.\n\n| Week | Event ID | Title | Passages | Major-choice targets |\n|---|---|---|---:|---|\n';
for(const n of rows){const pages=Object.values(graph).filter(p=>(p.originId||p.id)===n.id);md+=`| ${n.chapter} | ${n.id} | ${n.title} | ${pages.length} | ${[...new Set(graph[n.id].choices.map(c=>c.target))].join(', ')} |\n`;}
md+='\n## Epilogues\n\nCategory is selected first by the academic/consent rules. Within that category, `pickEnding` in `data/story.js` evaluates its explicit priority list, selecting the first matching flag or the unconditional fallback. Flags can overlap; there is always exactly one selected variant.\n\n| ID | Stars | Title | Required route flag |\n|---|---:|---|---|\n';
for(const e of endingVariants)md+=`| ${e.id} | ${e.rating} | ${e.title} | ${e.when?.path||'Fallback'} |\n`;
writeFileSync(new URL('../docs/STORY_GRAPH.md',import.meta.url),md);
const report=[];
for(const [style,wrong,pursue]of [['independent',false,false],['social',false,false],['balanced',false,false],['independent',false,true],['social',false,true],['balanced',false,true],['balanced',true,false]]){const s=play(style,42,wrong,pursue);report.push({style,wrongExamAnswers:wrong,pursueDating:pursue,grade:average(s),stars:rating(s),ending:pickEnding(s).id,decisions:s.choiceHistory.length,cash:s.cash,stats:s.stats});}
writeFileSync(new URL('../docs/ROUTE_RESULTS.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
console.log('Graph reference and seven route reports written.');
